variables: 
  APP_PORT: 8080
  APP_HOST: 0.0.0.0
  IMAGE_TAG: lucaslemo/flask:1.0.0

stages:
  - build
  - image_scan
  - deploy

build_job:
   stage: build
   image: docker:20.10.16
   services:
       - docker:20.10.16-dind
   script:
       - docker build --build-arg PORT=$APP_PORT -t $IMAGE_TAG -f ./docker/flask/Dockerfile .

security_scan:
  stage: image_scan
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  before_script:
    - apk add --no-cache curl
    - curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
  script:
    - trivy image --ignore-unfixed --severity HIGH,CRITICAL $IMAGE_TAG

deploy_job:
    stage: deploy
    image: docker:20.10.16
    services:
        - docker:20.10.16-dind
    before_script:
        - cp /usr/hdb/.env /builds/var/www/app/.env
        - docker compose down
        - PORT_CONTAINERS=$(docker ps --filter "publish=$APP_PORT" -q)
        - echo $PORT_CONTAINERS
        - if [ -n "$PORT_CONTAINERS" ]; then
            docker stop $PORT_CONTAINERS;
            docker rm $PORT_CONTAINERS;
            sleep 5; 
          fi
    script:
        - docker compose up -d