variables: 
  APP_PORT: 8080
  APP_HOST: 0.0.0.0
  IMAGE_TAG: lucaslemo/flask:1.0.0

stages:
  - build
  - deploy

build_job:
   stage: build
   image: docker:20.10.16
   services:
       - docker:20.10.16-dind
   script:
       - docker build --build-arg PORT=$APP_PORT -t $IMAGE_TAG -f ./docker/flask/Dockerfile .

deploy_job:
    stage: deploy
    image: docker:20.10.16
    services:
        - docker:20.10.16-dind
    before_script:
        - echo "Remove containers antigos"
        - PORT_CONTAINERS=$(docker ps --filter "publish=$APP_PORT" -q)
        - echo $PORT_CONTAINERS
        - if [ -n "$PORT_CONTAINERS" ]; then
            docker stop $PORT_CONTAINERS;
            docker rm $PORT_CONTAINERS;
            sleep 5; 
          fi
    script:
        - echo "Deploy do app"
        - cp .env.example .env
        - docker compose up -d --build