services:
  web:
    image: 'lucaslemo/flask:1.0.0'
    build:
      context: .
      dockerfile: docker/flask/Dockerfile
      args:
        - port=${APP_PORT}
    container_name: flask
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - ./todo_project:/app
      - /dev/log:/dev/log
    environment:
      FLASK_ENV: ${FLASK_ENV}
      FLASK_DEBUG: ${FLASK_DEBUG}
      SECRET_KEY: ${SECRET_KEY}
      DATABASE_URL: ${DATABASE_URL}
      PYTHONUNBUFFERED: 1
    restart: always
    command: gunicorn --bind "${APP_HOST}:${APP_PORT}" todo_project:app
