services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    user: '1000:1000'
    volumes:
      - ./docker/prometheus:/etc/prometheus:rw
      - ./docker/prometheus/data:/prometheus:rw
    networks:
      - todo_project
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana
    container_name: grafana
    user: '1000:1000'
    environment:
      GF_INSTALL_PLUGINS: 'grafana-clock-panel,grafana-simple-json-datasource'
      GF_SECURITY_ADMIN_USER: 'admin'
      GF_SECURITY_ADMIN_PASSWORD: 'admin'
      GF_USERS_ALLOW_SIGN_UP: 'false'
    volumes:
      - ./docker/grafana/data:/var/lib/grafana:rw
    ports:
      - 3000:3000
    networks:
      - todo_project
    depends_on:
      - prometheus

networks:
  todo_project:
    name: todo_project
    external: true