services:
  web:
    image: 'lucaslemo/flask:1.0.0'
    build:
      context: .
      dockerfile: docker/flask/Dockerfile
    container_name: flask
    ports:
      - "${APP_PORT:-5000}:5000"
    volumes:
      - ./todo_project:/app
    environment:
      FLASK_ENV: ${FLASK_ENV}
      FLASK_DEBUG: ${FLASK_DEBUG}
      SECRET_KEY: ${SECRET_KEY}
      DATABASE_URL: ${DATABASE_URL}
      PYTHONUNBUFFERED: 1
    restart: always
    command: gunicorn --bind 0.0.0.0:5000 todo_project:app