services:
  web:
    image: 'lucaslemo/flask:1.0.0'
    build:
      context: .
      dockerfile: docker/flask/Dockerfile
      args:
        - PORT=${APP_PORT}
    container_name: flask
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - /usr/hdb/db:/usr/hdb/db:rw
      - /dev/log:/dev/log:rw
      - ./todo_project:/var/www/app
    environment:
      FLASK_ENV: ${FLASK_ENV}
      FLASK_DEBUG: ${FLASK_DEBUG}
      SECRET_KEY: ${SECRET_KEY}
      DATABASE_URL: ${DATABASE_URL}
      PYTHONUNBUFFERED: 1
    networks:
      - todo_project
    restart: always
    command: gunicorn --bind "${APP_HOST}:${APP_PORT}" todo_project:app

networks:
  todo_project:
    name: todo_project
    external: true